In [60]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.preprocessing import*
%matplotlib inline

## Question 1

In [61]:
from sklearn.datasets import load_digits

digit = load_digits()
X = digit.data
Y = digit.target

X.shape,Y.shape

((1797, 64), (1797,))

## Question 2

In [62]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)
X_std

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

## Question 4

In [63]:
from sklearn.decomposition import PCA
pca = PCA(n_components=16)

In [64]:
principalComponents = pca.fit_transform(X_std)
principalComponents

array([[ 1.91423526, -0.95448475, -3.94607378, ..., -0.20534803,
         0.80881593,  0.11709746],
       [ 0.58898468,  0.92465983,  3.92472334, ..., -0.3730926 ,
        -0.73839269, -0.20673423],
       [ 1.30203398, -0.31719986,  3.02338171, ..., -0.98563353,
        -1.13541249,  0.38192487],
       ...,
       [ 1.02257439, -0.14796788,  2.47001013, ...,  0.22943108,
         0.32595767,  1.14623143],
       [ 1.07611447, -0.38082674, -2.45561382, ..., -0.75658596,
        -0.09373994,  0.23058484],
       [-1.25766573, -2.22753044,  0.28357027, ...,  0.75345801,
         1.78347427,  0.29362417]])

In [65]:
principalDf = pd.DataFrame(data = principalComponents)
principalDf.head()

0         1         2         3         4         5         6   \
0  1.914235 -0.954485 -3.946074  2.028807 -0.266857  0.529290 -1.414219   
1  0.588985  0.924660  3.924723 -1.779959 -0.993270 -0.676377  1.878686   
2  1.302034 -0.317200  3.023382 -2.043379 -2.081455  0.935773 -1.298190   
3 -3.020770 -0.868790 -0.801698 -2.186977 -0.556450  0.728956  0.960224   
4  4.528903 -1.093503  0.973146 -1.419441 -1.716481  1.434510  1.071462   

         7         8         9         10        11        12        13  \
0  1.496637  0.132642 -0.817652 -0.501727 -0.791053  0.218766 -0.205348   
1  0.555994  1.083424  0.087820 -0.506942  0.636022 -0.055679 -0.373093   
2  1.154058  0.779893 -1.103442  2.194539 -2.309801 -0.555189 -0.985634   
3 -1.383076  0.252505  0.745837 -1.053396  0.497996 -0.158813  0.991481   
4 -0.966939 -1.676634  1.162543 -1.007922 -1.363323 -0.323332 -0.116237   

         14        15  
0  0.808816  0.117097  
1 -0.738393 -0.206734  
2 -1.135412  0.381925  
3 -0.166612 -1.044622  
4  0.788582  0.195904

In [66]:
principalDf = x

In [67]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444415, 0.06498408, 0.04860154,
       0.04214118, 0.03942072, 0.03389377, 0.02998102, 0.02931962,
       0.02781758, 0.02576983, 0.02275224, 0.02226773, 0.021627  ,
       0.01913305])

## Question 3

In [68]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.25)

## Question 5

In [69]:
from sklearn.linear_model import LogisticRegression
reg=LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [70]:
pred = reg.predict(x_test)

## Question 6

## a)

In [71]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.9644444444444444

## b)

In [72]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[55,  0,  0,  0,  1,  1,  0,  0,  0,  0],
       [ 0, 46,  0,  0,  0,  0,  0,  0,  2,  1],
       [ 0,  0, 47,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 30,  0,  1,  0,  0,  0,  0],
       [ 0,  1,  0,  0, 44,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 44,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 42,  0,  1,  0],
       [ 0,  1,  0,  0,  0,  0,  0, 41,  0,  0],
       [ 0,  1,  0,  1,  0,  1,  0,  0, 40,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  3, 45]], dtype=int64)

## c)

In [73]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.96      0.98        57
          1       0.94      0.94      0.94        49
          2       1.00      0.98      0.99        48
          3       0.94      0.97      0.95        31
          4       0.98      0.98      0.98        45
          5       0.94      1.00      0.97        44
          6       1.00      0.98      0.99        43
          7       1.00      0.98      0.99        42
          8       0.87      0.93      0.90        43
          9       0.98      0.94      0.96        48

avg / total       0.97      0.96      0.96       450

