In [1]:
from sklearn import datasets
import numpy as np
from sklearn import metrics
import pandas as pd
from sklearn.svm import SVC

## Question 1

In [2]:
digit = datasets.load_digits()
x = digit.data
y = digit.target

## Question 2

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25)
x_train.shape, x_test.shape

((1347, 64), (450, 64))

## Question 3

## a)

In [36]:
model = SVC(kernel='linear')

In [37]:
model.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [38]:
pred = model.predict(x_test)

In [39]:
metrics.accuracy_score(y_test,pred)

0.9866666666666667

In [40]:
print(metrics.classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.97      1.00      0.99        37
          1       0.93      1.00      0.96        40
          2       1.00      0.98      0.99        49
          3       0.98      1.00      0.99        49
          4       1.00      1.00      1.00        48
          5       1.00      0.98      0.99        44
          6       1.00      0.98      0.99        47
          7       1.00      1.00      1.00        54
          8       1.00      0.95      0.97        37
          9       0.98      0.98      0.98        45

avg / total       0.99      0.99      0.99       450



In [41]:
print(metrics.confusion_matrix(y_test,pred))

[[37  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]
 [ 0  1 48  0  0  0  0  0  0  0]
 [ 0  0  0 49  0  0  0  0  0  0]
 [ 0  0  0  0 48  0  0  0  0  0]
 [ 0  0  0  0  0 43  0  0  0  1]
 [ 1  0  0  0  0  0 46  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  0]
 [ 0  2  0  0  0  0  0  0 35  0]
 [ 0  0  0  1  0  0  0  0  0 44]]


## b)

In [105]:
model2 = SVC(kernel='poly')

In [106]:
model2.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [107]:
pred2 = model2.predict(x_test)

In [108]:
metrics.accuracy_score(y_test,pred2)

0.9911111111111112

In [109]:
print(metrics.classification_report(y_test,pred2))

             precision    recall  f1-score   support

          0       0.97      1.00      0.99        37
          1       0.98      1.00      0.99        40
          2       1.00      1.00      1.00        49
          3       1.00      1.00      1.00        49
          4       1.00      1.00      1.00        48
          5       1.00      0.95      0.98        44
          6       0.98      0.98      0.98        47
          7       1.00      1.00      1.00        54
          8       1.00      0.97      0.99        37
          9       0.98      1.00      0.99        45

avg / total       0.99      0.99      0.99       450



In [110]:
print(metrics.confusion_matrix(y_test,pred2))

[[37  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]
 [ 0  0 49  0  0  0  0  0  0  0]
 [ 0  0  0 49  0  0  0  0  0  0]
 [ 0  0  0  0 48  0  0  0  0  0]
 [ 0  0  0  0  0 42  1  0  0  1]
 [ 1  0  0  0  0  0 46  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  0]
 [ 0  1  0  0  0  0  0  0 36  0]
 [ 0  0  0  0  0  0  0  0  0 45]]


## c)

In [88]:
model3 = SVC(C=1.5)

In [89]:
model3.fit(x_train,y_train)

SVC(C=1.5, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [90]:
pred3 = model3.predict(x_test)

In [91]:
metrics.accuracy_score(y_test,pred3)

0.5755555555555556

In [92]:
print(metrics.classification_report(y_test,pred3))

             precision    recall  f1-score   support

          0       1.00      0.54      0.70        37
          1       1.00      0.68      0.81        40
          2       1.00      0.31      0.47        49
          3       1.00      0.53      0.69        49
          4       1.00      0.60      0.75        48
          5       1.00      0.86      0.93        44
          6       1.00      0.62      0.76        47
          7       1.00      0.35      0.52        54
          8       0.16      1.00      0.28        37
          9       1.00      0.42      0.59        45

avg / total       0.93      0.58      0.65       450



In [111]:
print(metrics.confusion_matrix(y_test,pred3))

[[20  0  0  0  0  0  0  0 17  0]
 [ 0 27  0  0  0  0  0  0 13  0]
 [ 0  0 15  0  0  0  0  0 34  0]
 [ 0  0  0 26  0  0  0  0 23  0]
 [ 0  0  0  0 29  0  0  0 19  0]
 [ 0  0  0  0  0 38  0  0  6  0]
 [ 0  0  0  0  0  0 29  0 18  0]
 [ 0  0  0  0  0  0  0 19 35  0]
 [ 0  0  0  0  0  0  0  0 37  0]
 [ 0  0  0  0  0  0  0  0 26 19]]


## d)

In [66]:
model4 = SVC(kernel='sigmoid')

In [67]:
model4.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [68]:
pred4 = model4.predict(x_test)

In [69]:
metrics.accuracy_score(y_test,pred4)

0.08888888888888889

In [70]:
print(metrics.classification_report(y_test,pred4))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        37
          1       0.09      1.00      0.16        40
          2       0.00      0.00      0.00        49
          3       0.00      0.00      0.00        49
          4       0.00      0.00      0.00        48
          5       0.00      0.00      0.00        44
          6       0.00      0.00      0.00        47
          7       0.00      0.00      0.00        54
          8       0.00      0.00      0.00        37
          9       0.00      0.00      0.00        45

avg / total       0.01      0.09      0.01       450



C:\Users\DELLPC\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [71]:
print(metrics.confusion_matrix(y_test,pred4))

[[ 0 37  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  0  0]
 [ 0 48  0  0  0  0  0  0  0  0]
 [ 0 44  0  0  0  0  0  0  0  0]
 [ 0 47  0  0  0  0  0  0  0  0]
 [ 0 54  0  0  0  0  0  0  0  0]
 [ 0 37  0  0  0  0  0  0  0  0]
 [ 0 45  0  0  0  0  0  0  0  0]]
