In [28]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.datasets import load_wine
from sklearn.preprocessing import*
%matplotlib inline

## Question 1

In [29]:
data = load_wine()

In [30]:
x = data.data
y = data.target

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.25)
X_train.shape , X_test.shape

((133, 13), (45, 13))

## Question 2

## a)

In [32]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [33]:
bagging = BaggingClassifier(base_estimator=model,max_samples=0.5, max_features=0.5)

In [34]:
bagging.fit(X_train,Y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=0.5,
         max_samples=0.5, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [35]:
pred = bagging.predict(X_test)

In [36]:
metrics.accuracy_score(Y_test,pred)

0.9555555555555556

In [37]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test,pred)

array([[15,  0,  0],
       [ 0, 16,  1],
       [ 0,  1, 12]], dtype=int64)

In [38]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       0.94      0.94      0.94        17
          2       0.92      0.92      0.92        13

avg / total       0.96      0.96      0.96        45



## b)

In [39]:
from sklearn.ensemble import RandomForestClassifier
model1 = RandomForestClassifier(criterion='entropy',max_leaf_nodes=40)
model1.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=40,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [40]:
pred1 = model1.predict(X_test)
metrics.accuracy_score(Y_test,pred1)

0.9777777777777777

In [41]:
confusion_matrix(Y_test,pred1)

array([[14,  1,  0],
       [ 0, 17,  0],
       [ 0,  0, 13]], dtype=int64)

In [42]:
print(classification_report(Y_test,pred1))

             precision    recall  f1-score   support

          0       1.00      0.93      0.97        15
          1       0.94      1.00      0.97        17
          2       1.00      1.00      1.00        13

avg / total       0.98      0.98      0.98        45



## c)

In [43]:
from sklearn.ensemble import GradientBoostingClassifier
model2 = GradientBoostingClassifier(n_estimators=10, learning_rate=1.0,max_depth=1, random_state=0)
model2.fit(X_train, Y_train) 

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=1.0, loss='deviance', max_depth=1,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=10,
              presort='auto', random_state=0, subsample=1.0, verbose=0,
              warm_start=False)

In [44]:
pred2 = model2.predict(X_test)

In [45]:
metrics.accuracy_score(Y_test,pred2)

1.0

In [46]:
confusion_matrix(Y_test,pred2)

array([[15,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 13]], dtype=int64)

In [47]:
print(classification_report(Y_test,pred2))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       1.00      1.00      1.00        17
          2       1.00      1.00      1.00        13

avg / total       1.00      1.00      1.00        45



## d)

In [48]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC

In [49]:
model3 = DecisionTreeClassifier()
model4 = LogisticRegression()
model5 = SVC()
final_model = VotingClassifier(estimators = [('DT',model3),('LR',model4),('SVC',model5)])

In [50]:
final_model.fit(X_train,Y_train)

VotingClassifier(estimators=[('DT', DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [51]:
pred_final = final_model.predict(X_test)

C:\Users\DELLPC\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [52]:
metrics.accuracy_score(Y_test,pred_final)

0.9333333333333333

In [53]:
confusion_matrix(Y_test,pred_final)

array([[14,  1,  0],
       [ 0, 17,  0],
       [ 0,  2, 11]], dtype=int64)

In [54]:
print(classification_report(Y_test,pred_final))

             precision    recall  f1-score   support

          0       1.00      0.93      0.97        15
          1       0.85      1.00      0.92        17
          2       1.00      0.85      0.92        13

avg / total       0.94      0.93      0.93        45

